---
- name: Fail if unsupported system detected
  fail:
    msg: "System {{ ansible_distribution }} is not support by this role"
  when: ansible_distribution not in supported_systems

- name: Fail if no elasticsearch_hosts var
  fail:
    msg: "Please provide array of elasticsearch hosts in 'elasticsearch_hosts' variable"
  when: elasticsearch_hosts is undefined
